name: CI
on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pdf:
    name: Build and release pdf
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: EAL_Apuntes_Adrián_Lattes.tex
        
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.eps,*.pdf,*.md, *.tex"
          prerelease: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
